# Generated by Django 4.2.26 on 2026-02-22 05:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UsedSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, help_text='Optional part number', max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('whole_price', models.DecimalField(decimal_places=2, help_text='Price for the entire used part', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('initial_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('sold_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('can_be_broken_down', models.BooleanField(default=True, help_text='Can this part be sold in components?')),
                ('is_broken_down', models.BooleanField(default=False, help_text='Has this been broken into components?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_parts', to='stock.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, help_text='Optional part number', max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('initial_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sold_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_stock_level', models.IntegerField(default=5, help_text='Alert when stock falls below this level', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_parts', to='stock.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('initial_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('sold_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('used_spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='stock.usedsparepart')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='usedsparepart',
            index=models.Index(fields=['part_number'], name='stock_useds_part_nu_a89fab_idx'),
        ),
        migrations.AddIndex(
            model_name='usedsparepart',
            index=models.Index(fields=['name'], name='stock_useds_name_1c6fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='newsparepart',
            index=models.Index(fields=['part_number'], name='stock_newsp_part_nu_8010f0_idx'),
        ),
        migrations.AddIndex(
            model_name='newsparepart',
            index=models.Index(fields=['name'], name='stock_newsp_name_51302c_idx'),
        ),
    ]
