# Generated by Django 6.0.2 on 2026-02-28 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_authorizations', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_authorization', to='stock.sale')),
            ],
            options={
                'verbose_name': 'Stock Authorization',
                'verbose_name_plural': 'Stock Authorizations',
                'ordering': ['-authorized_at'],
                'indexes': [models.Index(fields=['authorized_at'], name='stock_stock_authori_1d3574_idx'), models.Index(fields=['-authorized_at'], name='stock_stock_authori_2ddb6d_idx')],
            },
        ),
    ]
