# Generated by Django 4.2.26 on 2026-02-22 14:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_customer_sale_saleitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('new', 'New Spare Part'), ('used', 'Used Spare Part'), ('component', 'Component')], max_length=20)),
                ('product_id', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('quantity_added', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('previous_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('new_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.CharField(default='Stock replenishment', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_type', 'product_id'], name='stock_stock_product_26e4a8_idx'), models.Index(fields=['created_at'], name='stock_stock_created_42df94_idx')],
            },
        ),
    ]
