# Generated by Django 4.2.26 on 2026-02-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for debt payment', null=True),
        ),
    ]
