# Generated by Django 6.0.2 on 2026-02-26 08:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_cardiagnosis_diagnosis_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Opening balance amount for the month', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('previous_month_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance carried forward from previous month', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opening Balance',
                'verbose_name_plural': 'Opening Balances',
                'ordering': ['-month'],
                'unique_together': {('month',)},
            },
        ),
    ]
