# Generated by Django 6.0.2 on 2026-02-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('stock', 'Stock'), ('garage', 'Garage')], max_length=10),
        ),
    ]
