# Generated by Django 6.0.2 on 2026-02-28 12:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('repair_description', models.TextField(help_text='What was fixed on the vehicle')),
                ('labor_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale_receipt_number', models.CharField(blank=True, help_text='Receipt number from sales', max_length=50, null=True)),
                ('parts_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garage_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garage Invoice',
                'verbose_name_plural': 'Garage Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('from_sale_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='garage.garageinvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plate_number'], name='garage_vehi_plate_n_516685_idx'), models.Index(fields=['-created_at'], name='garage_vehi_created_c50186_idx')],
            },
        ),
        migrations.AddField(
            model_name='garageinvoice',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='garage.vehicle'),
        ),
        migrations.AddIndex(
            model_name='garageinvoice',
            index=models.Index(fields=['invoice_number'], name='garage_gara_invoice_e4c4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='garageinvoice',
            index=models.Index(fields=['-created_at'], name='garage_gara_created_6941b4_idx'),
        ),
        migrations.AddIndex(
            model_name='garageinvoice',
            index=models.Index(fields=['status'], name='garage_gara_status_3a1637_idx'),
        ),
    ]
